-- FK 사용

CREATE TABLE SCHOOL(
	SCHOOL_ID NUMBER,
	NAME VARCHAR2(1000),
	CONSTRAINT PK_SCHOOL PRIMARY KEY(SCHOOL_ID)
);

CREATE TABLE STUDENT(
	STUDENT_ID NUMBER,
	NAME VARCHAR2(1000),
	AGE NUMBER,
	SCHOOL_ID NUMBER,
	CONSTRAINT PK_STUDENT PRIMARY KEY(STUDENT_ID),
	CONSTRAINT FK_STUDENT FOREIGN KEY(SCHOOL_ID) 
		REFERENCES SCHOOL(SCHOOL_ID)
);

INSERT INTO SCHOOL(SCHOOL_ID, NAME)
VALUES(1, 'DBMS 고등학교');

INSERT INTO SCHOOL(SCHOOL_ID, NAME)
VALUES(2, 'JAVA 고등학교');

INSERT INTO SCHOOL(SCHOOL_ID, NAME)
VALUES(3, 'PYTHON 고등학교');

SELECT * FROM SCHOOL s ;

-- 오류 발생!
-- FK인 SCHOOL_ID에 참조하는 칼럼의 값만 넣을 수 있다.
-- 10번 학교는 존재하지 않으므로 오류가 발생된다.
INSERT INTO STUDENT
(STUDENT_ID, NAME, AGE, SCHOOL_ID)
VALUES(1, '김철수', 17, 10);



INSERT INTO STUDENT
(STUDENT_ID, NAME, AGE, SCHOOL_ID)
VALUES(1, '김철수', 17, 1);

INSERT INTO STUDENT
(STUDENT_ID, NAME, AGE, SCHOOL_ID)
VALUES(2, '짱구', 17, 1);

INSERT INTO STUDENT
(STUDENT_ID, NAME, AGE, SCHOOL_ID)
VALUES(3, '유리', 18, 2);

INSERT INTO STUDENT
(STUDENT_ID, NAME, AGE, SCHOOL_ID)
VALUES(4, '영희', 19, 2);


SELECT *FROM STUDENT s ;


-- 기타 제약조건
DROP TABLE STUDENT ;

CREATE TABLE STUDENT(
	STUDENT_ID NUMBER,
	PHONE_NUMBER VARCHAR2(1000),
	NAME VARCHAR2(1000),
	MAJOR VARCHAR2(1000),
	GENDER CHAR(1) DEFAULT 'N' NOT NULL,
	CONSTRAINT PK_STUDENT PRIMARY KEY (STUDENT_ID),
	CONSTRAINT UN_STUDENT UNIQUE (PHONE_NUMBER),
	CONSTRAINT CH_STUDENT CHECK (GENDER IN ('M','F'))
);

INSERT INTO STUDENT
(STUDENT_ID, PHONE_NUMBER, NAME, MAJOR, GENDER)
VALUES(1, '010-1111-1111', '김철수', '컴공', 'M' );

-- 유니크 제약조건은 NULL은 허용
-- 중복은 허용 안함
INSERT INTO STUDENT
(STUDENT_ID, PHONE_NUMBER, NAME, MAJOR, GENDER)
VALUES(2, NULL, '신짱구', '컴공', 'M' );

INSERT INTO STUDENT
(STUDENT_ID, PHONE_NUMBER, NAME, MAJOR, GENDER)
VALUES(3, '010-2222-2222', '신짱구', '컴공', 'M' );

INSERT INTO STUDENT
(STUDENT_ID, PHONE_NUMBER, NAME, MAJOR, GENDER)
VALUES(4, '010-3333-3333', '이유리', '컴공', 'F' );

INSERT INTO STUDENT
(STUDENT_ID, PHONE_NUMBER, NAME, MAJOR)
VALUES(5, '010-4444-4444', '김영희', '컴공' );

SELECT *FROM STUDENT s ;


-- 복합키
CREATE TABLE FLOWER(
	NAME VARCHAR2(1000),
	COLOR VARCHAR2(1000),
	PRICE NUMBER,
	CONSTRAINT PK_FLOWER PRIMARY KEY(NAME, COLOR)
);

INSERT INTO FLOWER
(NAME, COLOR, PRICE)
VALUES('해바라기', '빨강', 5000);

INSERT INTO FLOWER
(NAME, COLOR, PRICE)
VALUES('해바라기', '노랑', 4000);

INSERT INTO FLOWER
(NAME, COLOR, PRICE)
VALUES('튤립', '빨강', 10000);

INSERT INTO FLOWER
(NAME, COLOR, PRICE)
VALUES('튤립', '노랑', 8000);

INSERT INTO FLOWER
(NAME, COLOR, PRICE)
VALUES('튤립', '노랑', 8000);

SELECT * FROM FLOWER f ;
















